name: 2025 deploy azure optimized

env:
  NPM_TOKEN: ${{ secrets.NPM1_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
  GA_CODE: ${{ secrets.GA_MEASUREMENT_ID }}
  NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
  NEXT_PUBLIC_GA_CODE: ${{ secrets.GA_MEASUREMENT_ID }}
  BUILD_TARGET: ${{ secrets.BUILD_TARGET}}

on:
  push:
    branches:
      - s_azure_test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        env:
          GA_CODE: ${{ secrets.GA_MEASUREMENT_ID }}
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_GA_CODE: ${{ secrets.GA_MEASUREMENT_ID }}
          GA_TRACKING_CODE: ${{ secrets.GA_MEASUREMENT_ID }}
        run: npm ci --legacy-peer-deps

      - name: Run build script
        run: npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "node_modules/webpack*" "node_modules/.bin" "*.git/*" "*.log"
          echo "Size of release.zip: $(du -sh release.zip | awk '{print $1}')"          

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: search-node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: search-node-app
          path: . 

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'core-search'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BCA28C303AFF490AA6E9231236FD8202 }}
          package: release.zip
