name: Trigger auto deployment for core-containerapp-search

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ containerapp_deploy ]
    paths:
    - '**'
    - '.github/workflows/core-containerapp-search-AutoDeployTrigger-8c6d7424-0aef-4539-bd4e-20b13502237f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.CORECONTAINERAPPSEARCH_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: corefrontend.azurecr.io
          registryUsername: ${{ secrets.CORECONTAINERAPPSEARCH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CORECONTAINERAPPSEARCH_REGISTRY_PASSWORD }}
          containerAppName: core-containerapp-search
          resourceGroup: test-rg
          imageToBuild: corefrontend.azurecr.io/core-containerapp-search:${{ github.sha }}
          
            

     

