name: containerapp deploy azure

on:
  # push:
  #   branches:
  #     - containerapp_deploy
  workflow_dispatch: 

env:
  ACR_NAME: corefrontend
  IMAGE_NAME: search
  RESOURCE_GROUP: test-rg
  CONTAINERAPP_NAME: core-containerapp-search
  CONTAINER_PORT: 80
  NPM_TOKEN: ${{ secrets.NPM1_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
  GA_CODE: ${{ secrets.GA_MEASUREMENT_ID }}
  NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
  NEXT_PUBLIC_GA_CODE: ${{ secrets.GA_MEASUREMENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Git SHA tag
        id: vars
        run: echo "tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Docker Build and Tag
        run: |
          docker build \
            --build-arg NPM_TOKEN=${{ secrets.NPM1_TOKEN }} \
            --build-arg API_KEY=${{ secrets.API_KEY }} \
            --build-arg USE_MOCK_DATA=true \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }} \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Docker Push
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set image tag from build job
        run: echo "TAG=${{ needs.build-and-push.outputs.tag }}" >> $GITHUB_ENV

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.CONTAINERAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --container-name ${{ env.IMAGE_NAME }}
